### ISSUE TITLE
Stol

### ISSUE THREAD

**Issue by AdamHjalmarsson99** [t0883/Clean-API-Group-Assignment#14]
- [x] #181
- [x] #182
- [x] #183
- [x] #184
- [x] #185
- [x] #186
- [ ] #187
- [ ] Skapa http post
- [ ] Skapa http get all
- [ ] Skapa http get by id
- [ ] Skapa http put
- [ ] Skapa http delete
- [ ] Ta bord brand från stol

**Comment by GabrielllaAslan** [comment]
> * [x]  [Skapa modell för stol #181](https://github.com/t0883/Clean-API-Group-Assignment/issues/181)
> * [ ]  [Skapa controller för stol #182](https://github.com/t0883/Clean-API-Group-Assignment/issues/182)
> * [x]  [Skapa QueryHandler #183](https://github.com/t0883/Clean-API-Group-Assignment/issues/183)
> * [x]  [Skapa CommandHandlers #184](https://github.com/t0883/Clean-API-Group-Assignment/issues/184)
> * [x]  [Koppla modellen till databas #185](https://github.com/t0883/Clean-API-Group-Assignment/issues/185)
> * [x]  [Skapa Repository #186](https://github.com/t0883/Clean-API-Group-Assignment/issues/186)
> * [ ]  [Tester för stol #187](https://github.com/t0883/Clean-API-Group-Assignment/issues/187)
> * [ ]  Skapa http post
> * [ ]  Skapa http get all
> * [ ]  Skapa http get by id
> * [ ]  Skapa http put
> * [ ]  Skapa http delete
> * [ ]  Ta bord brand från stol
